name: o_b_d2_scanner_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
<<<<<<< HEAD
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^5.6.8
  cloud_firestore_platform_interface: ^6.6.8
  cloud_firestore_web: ^4.4.8
  collection: 1.19.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  firebase_auth_platform_interface: ^7.6.3
  firebase_auth_web: ^5.14.3
  firebase_core: ^3.13.1
  firebase_core_platform_interface: ^5.4.0
  firebase_core_web: ^2.23.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_keyboard_visibility: 6.0.0
  flutter_keyboard_visibility_linux: 1.0.0
  flutter_keyboard_visibility_macos: 1.0.0
  flutter_keyboard_visibility_platform_interface: 2.0.0
  flutter_keyboard_visibility_web: 2.0.0
  flutter_keyboard_visibility_windows: 1.0.0
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  google_sign_in_android: ^6.2.1
  google_sign_in_ios: ^5.9.0
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  http: ^0.13.6
  intl: 0.19.0
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  stream_transform: ^2.1.1
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.2.3

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
=======

  # Core Flutter packages
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # UI and styling
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1

  # Navigation
  go_router: ^14.2.7
  page_transition: ^2.2.1

  # URL handling
  url_launcher: ^6.3.1

  # Utilities
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.19.0
  equatable: ^2.0.7
  from_css_color: ^2.0.0
  json_path: ^0.7.6

  # FlutterFlow compatibility packages
  flutter_cache_manager: ^3.4.1
  collection: ^1.19.1
  plugin_platform_interface: ^2.1.8
>>>>>>> f478dc7 (Update all files to ensure clean structure)

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

